<HomeScreen>:
    GridLayout:
        rows: 5

        Button:
            id: settings_button
            text: "Settings"
            on_press: root.manager.current = 'Settings'

        Button:
            id: light_button
            text: "Lights"
            on_press: root.manager.current = 'Lights'

        Button:
            id: exit_button
            text: "Quit"
            on_press: root.close_gui()
