<HomeScreen>:
    name: "home"

    HomeGrid:
        id: base_layout
        Button:
            text: "Delete"
            on_press: base_layout.numButtons = root.delete_but(base_layout.numButtons, base_layout.minButtons)
        Button:
            text: "Add"
            on_press: base_layout.numButtons = root.add_but(base_layout.numButtons, base_layout.maxButtons)
        Button:
            text: "Quit"
            on_press: root.close_gui()